version: 2

models:
      # Generate model
      - name: stg_commodities
        description: "staggin com valores historico das commodities"
        columns:
          - name: Date
            description: "Data da Obeservação"
          - name: Close
            description: "Preço de fechamento da commodity"
          - name: simbolo
            description: "Simbolo da commodity"

  # Generate model
      - name: valores
        description: "valores das commodities"
        columns:
          - name: Data
            description: "Data da Obeservação"
          - name: symbol
            description: "flag do tipo da commodities"
          - name: acao
            description: "valorr"
          - name: quantity
            description: "quantidade"

